import type { Project } from "@/lib/schemas";

/**
 * Initial project data. This is loaded into the database once (scripts/seed.ts)
 * and is also used as an offline fallback. After launch, manage projects from /admin.
 *
 * Client names are intentionally anonymised. Figures come from the resume.
 */
export const seedProjects: Project[] = [
  {
    slug: "enterprise-aiops-framework-telecom",
    title: "Enterprise-Grade AIOps Framework for Telecom Networks",
    summary:
      "MBA dissertation: a seven-layer reference architecture and operating model for predictive, increasingly autonomous IT and network operations.",
    category: "AI & Automation",
    project_type: "Academic",
    status: "Completed",
    year: 2026,
    role: "Author & researcher (IIM Lucknow MBA dissertation)",
    technologies: ["AIOps", "Observability", "Machine Learning", "ITSM", "Automation", "Network Operations"],
    key_features: [
      "Seven-layer reference architecture from data ingestion to executive intelligence",
      "Operating-model view: people, process and governance — not only tooling",
      "Phased maturity path from reactive to predictive to autonomous operations",
      "Security, compliance and human-in-the-loop controls built into the design",
    ],
    cover_image: null,
    screenshots: [],
    github_url: null,
    demo_url: null,
    demo_video_url: null,
    overview:
      "Telecom and enterprise network operations generate enormous volumes of alarms, logs, metrics and tickets. Most teams still work reactively: an event happens, a ticket is raised, an engineer investigates. This dissertation asks what a credible, enterprise-grade path to AI-enabled operations looks like — one that a large operator could actually govern and adopt.",
    problem:
      "Operations teams face alert fatigue, slow root-cause analysis and fragmented tooling. AIOps products promise automation, but organisations struggle to connect data sources, trust model outputs, integrate with ITSM processes and stay compliant. There is little practical guidance that combines architecture with operating model.",
    objectives:
      "- Define a reference architecture for enterprise-grade AIOps in telecom networks\n- Describe how it integrates with existing ITSM and operational processes\n- Propose a phased adoption model with governance and controls\n- Identify the organisational capabilities needed to sustain it",
    solution:
      "A prescriptive framework combining a seven-layer architecture with an operating model and a maturity roadmap. The emphasis is on sequencing: build data and observability foundations first, introduce correlation and noise reduction next, then move toward prediction and closed-loop automation with explicit human oversight.",
    architecture:
      "The reference architecture has seven layers:\n\n1. **Data ingestion** — telemetry, logs, events, topology and ticket data\n2. **Observability** — normalisation, correlation-ready storage, service mapping\n3. **AI engine** — anomaly detection, event correlation, prediction\n4. **Automation** — runbooks and closed-loop remediation with approval gates\n5. **ITSM integration** — incidents, problems and changes linked to AI insights\n6. **Security & compliance** — access control, auditability, model governance\n7. **Executive intelligence** — service health, risk and value reporting",
    workflow:
      "Signals flow from network and IT systems into the ingestion layer, are enriched with topology and service context, analysed by the AI engine, and surfaced as correlated incidents in ITSM. Approved automations execute through the automation layer, with every action logged for audit and fed back to improve the models.",
    implementation:
      "This is an academic framework. No commercial deployment is claimed. The work draws on published research, vendor-neutral architecture patterns and my experience running network and infrastructure programmes.",
    impact:
      "Provides a structured way for operations leaders to plan AIOps adoption as a business transformation rather than a tool purchase. *Placeholder: add any academic feedback or recognition here.*",
    challenges:
      "Balancing ambition (autonomous operations) with the realities of data quality, legacy tooling, change control and regulatory expectations in telecom.",
    lessons:
      "AIOps succeeds or fails on data foundations and operating model far more than on algorithms. Trust has to be earned in stages.",
    future:
      "Turn the framework into a self-assessment tool and a set of practitioner articles; explore a small proof-of-concept on open-source observability data.",
    is_case_study: true,
    featured: true,
    published: true,
    sort_order: 10,
  },
  {
    slug: "multi-site-network-modernisation",
    title: "Network Modernisation Across 200+ Sites",
    summary:
      "Led a $1M+ enterprise network modernisation programme for a global logistics client — from business case and roadmap to phased delivery.",
    category: "Networking & Telecom",
    project_type: "Professional",
    status: "Completed",
    year: 2024,
    role: "Technical Project Manager (BT)",
    technologies: ["LAN/WAN/WLAN", "SD-WAN", "Cisco", "Fortinet", "MS Project", "Jira"],
    key_features: [
      "Business case, charter and scope aligned to reliability and lifecycle risk",
      "Phased, site-by-site transformation roadmap",
      "Executive dashboards for budget, risk and progress",
      "Coordination of global vendors, engineering teams and client stakeholders",
    ],
    cover_image: null,
    screenshots: [],
    github_url: null,
    demo_url: null,
    demo_video_url: null,
    overview:
      "A global logistics client was running a large, ageing network estate across 200+ sites. Reliability issues and approaching end-of-life equipment created operational and security risk. I led the programme that turned these concerns into a structured, fundable modernisation roadmap and delivered it in phases.",
    problem:
      "End-of-life equipment, inconsistent site standards and limited visibility made the estate harder to support and riskier to change. The client needed modernisation without disrupting time-critical logistics operations.",
    objectives:
      "- Reduce lifecycle and operational risk across the estate\n- Standardise site designs where practical\n- Deliver in waves without disrupting business operations\n- Keep leadership informed with clear cost, risk and progress reporting",
    solution:
      "Developed the business case, project charter, scope and implementation strategy, then organised delivery into site waves with consistent pre-checks, change windows, validation and rollback steps.",
    architecture: "",
    workflow:
      "Site survey → design & bill of materials → lab validation → change approval → staged cutover → post-change validation → hypercare → handover to operations.",
    implementation:
      "Ran planning and governance with engineering, vendors and client stakeholders; maintained RAID logs and dependency tracking; and reported progress through executive dashboards covering budget utilisation, risk exposure and resourcing.",
    impact:
      "Delivered the modernisation programme end to end and earned client recognition for the delivery. *Placeholder: add measurable outcomes (e.g. availability, incident reduction) once verified.*",
    challenges:
      "Coordinating many sites, time zones and vendors while protecting operations; sequencing waves around business-critical periods.",
    lessons:
      "Standardised site playbooks and honest, early risk reporting matter more than any single technical decision.",
    future: "",
    is_case_study: true,
    featured: true,
    published: true,
    sort_order: 20,
  },
  {
    slug: "network-security-remediation-20000-devices",
    title: "Security Remediation Across 20,000+ Network Devices",
    summary:
      "Governed vulnerability remediation across a large LAN/WAN/WLAN/SD-WAN estate while protecting service continuity.",
    category: "Networking & Telecom",
    project_type: "Professional",
    status: "Completed",
    year: 2025,
    role: "Technical Project Manager (BT)",
    technologies: ["Network Security", "Cisco", "Fortinet", "Meraki", "SD-WAN", "ServiceNow"],
    key_features: [
      "Risk-based prioritisation of remediation waves",
      "Change governance balancing security urgency with uptime",
      "Progress tracking across a very large device population",
    ],
    cover_image: null,
    screenshots: [],
    github_url: null,
    demo_url: null,
    demo_video_url: null,
    overview:
      "Security vulnerabilities had to be remediated across more than 20,000 network devices of different types and generations. The challenge was to move quickly on risk while avoiding outages caused by the remediation itself.",
    problem:
      "A large, heterogeneous estate with varying criticality meant that a single 'patch everything' approach would either be too slow or too risky.",
    objectives:
      "- Reduce security exposure in priority order\n- Avoid service disruption from remediation changes\n- Provide clear visibility of progress and residual risk",
    solution:
      "Grouped devices by criticality and exposure, defined remediation waves, and aligned change windows with operations teams. Progress and residual risk were tracked and reported to stakeholders.",
    architecture: "",
    workflow: "Identify → prioritise → plan wave → approve change → remediate → validate → report.",
    implementation: "",
    impact: "Remediation governed at scale while maintaining service continuity and delivery commitments.",
    challenges: "Competing priorities between security urgency and change freeze periods.",
    lessons: "Prioritisation and transparency are what keep large remediation programmes moving.",
    future: "",
    is_case_study: false,
    featured: false,
    published: true,
    sort_order: 30,
  },
  {
    slug: "data-centre-migration-cisco-fortinet",
    title: "Data-Centre Migration & Infrastructure Upgrade",
    summary:
      "Orchestrated a data-centre migration with Cisco switching/routing and Fortinet firewall upgrades using lab testing, rollback planning and UAT.",
    category: "Networking & Telecom",
    project_type: "Professional",
    status: "Completed",
    year: 2023,
    role: "Technical Project Manager (BT)",
    technologies: ["Data Centre", "Cisco", "Fortinet", "Routing & Switching", "Firewalls"],
    key_features: ["Lab testing before production changes", "Documented rollback strategy", "User acceptance testing and hypercare"],
    cover_image: null,
    screenshots: [],
    github_url: null,
    demo_url: null,
    demo_video_url: null,
    overview:
      "A data-centre migration combined with switch, router and firewall upgrades — the kind of change where one missed dependency can take down critical services.",
    problem: "Ageing data-centre infrastructure needed to move and modernise with minimal downtime.",
    objectives: "- Migrate safely within agreed change windows\n- Upgrade core network and security platforms\n- Validate services before handing back to operations",
    solution: "Structured planning with lab validation, detailed cutover runbooks, explicit rollback criteria and UAT with application owners.",
    architecture: "",
    workflow: "Discovery → dependency mapping → lab build → runbook → cutover → validation/UAT → hypercare.",
    implementation: "",
    impact: "Migration and upgrades completed through structured planning and validation.",
    challenges: "Dependency discovery and coordinating application owners for UAT.",
    lessons: "A rehearsed rollback plan is what gives everyone the confidence to proceed.",
    future: "",
    is_case_study: false,
    featured: true,
    published: true,
    sort_order: 40,
  },
  {
    slug: "nordic-wireless-refresh",
    title: "Nordic Wireless Refresh — 5,000+ Access Points",
    summary:
      "Supported delivery of a $1.5M wireless refresh across Nordic regions, migrating 5,000+ access points to Cisco 9100 series.",
    category: "Networking & Telecom",
    project_type: "Professional",
    status: "Completed",
    year: 2022,
    role: "Technical Project Assistant (HCLTech)",
    technologies: ["WLAN", "Cisco 9100", "Wireless", "RAID management"],
    key_features: ["Multi-country rollout coordination", "RAID and decision log ownership", "Vendor and client reporting"],
    cover_image: null,
    screenshots: [],
    github_url: null,
    demo_url: null,
    demo_video_url: null,
    overview: "A large wireless refresh to improve network capability and end-user experience across multiple Nordic countries.",
    problem: "Legacy access points limited capacity and user experience.",
    objectives: "- Replace legacy access points at scale\n- Minimise disruption to users\n- Keep stakeholders aligned on progress and risk",
    solution: "Wave-based rollout with clear reporting, RAID management and coordination between technical teams, vendors and client stakeholders.",
    architecture: "",
    workflow: "",
    implementation: "",
    impact: "5,000+ access points migrated to Cisco 9100 series.",
    challenges: "Coordinating across countries, sites and vendors.",
    lessons: "Disciplined RAID management is the backbone of large rollouts.",
    future: "",
    is_case_study: false,
    featured: false,
    published: true,
    sort_order: 50,
  },
  {
    slug: "data-voice-rightsizing",
    title: "Data & Voice Utilisation Rightsizing",
    summary:
      "Analysed Data & Voice utilisation and built a rightsizing recommendation identifying ~$240k in annual savings.",
    category: "Data & Analytics",
    project_type: "Professional",
    status: "Completed",
    year: 2026,
    role: "Technical Account Manager (Accenture)",
    technologies: ["Data analysis", "Excel", "Technology financial management", "Data & Voice"],
    key_features: ["Utilisation vs. demand analysis", "Savings model", "Recommendation aligned to business demand"],
    cover_image: null,
    screenshots: [],
    github_url: null,
    demo_url: null,
    demo_video_url: null,
    overview: "A cost-optimisation analysis to align Data & Voice consumption with actual demand on an enterprise account.",
    problem: "Services were provisioned above actual demand, creating avoidable recurring cost.",
    objectives: "- Understand real utilisation\n- Identify rightsizing opportunities\n- Quantify savings without harming service",
    solution: "Compared provisioned capacity with observed utilisation and built a rightsizing recommendation.",
    architecture: "",
    workflow: "",
    implementation: "",
    impact: "Identified approximately $20k monthly / $240k annual savings opportunity.",
    challenges: "",
    lessons: "Commercial value often sits in data that operations teams already have.",
    future: "",
    is_case_study: false,
    featured: false,
    published: true,
    sort_order: 60,
  },
  {
    slug: "personal-brand-platform",
    title: "This Website — Personal Brand & Knowledge Platform",
    summary:
      "A full-stack Next.js and Supabase platform for projects, writing, videos, resources, consulting and mentoring enquiries — with a private admin.",
    category: "Web Applications",
    project_type: "Personal",
    status: "Ongoing",
    year: 2026,
    role: "Product owner",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL", "Vercel"],
    key_features: [
      "Data-driven content model for projects, articles, videos and resources",
      "Private admin dashboard protected by row-level security",
      "Validated enquiry forms with abuse protection",
      "SEO: structured data, sitemap, Open Graph",
    ],
    cover_image: null,
    screenshots: [],
    github_url: null,
    demo_url: null,
    demo_video_url: null,
    overview: "The site you're reading. Built to be a long-term home for my work, writing and services.",
    problem: "Professional profiles are scattered across LinkedIn, GitHub and documents, with no single place that shows the full picture.",
    objectives: "- One credible home for portfolio, writing and services\n- Easy publishing without touching code\n- Fast, accessible and search-friendly",
    solution: "A Next.js App Router site with content in Supabase (PostgreSQL), edited through a private admin area.",
    architecture:
      "- **Frontend:** Next.js (App Router), TypeScript, Tailwind CSS\n- **Data:** Supabase PostgreSQL with row-level security — public can read published content only\n- **Auth:** email magic-link sign-in restricted to the site owner\n- **Storage:** Supabase Storage for images and downloadable resources\n- **Hosting:** Vercel",
    workflow: "",
    implementation: "",
    impact: "",
    challenges: "",
    lessons: "",
    future: "Newsletter, consultation booking, paid templates and an AI career assistant.",
    is_case_study: false,
    featured: false,
    published: true,
    sort_order: 70,
  },
];
